BethanysPieShop/BethanysPieShop/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BethanysPieShop.Controllers
{
    public class ContactController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

BethanysPieShop/BethanysPieShop/Controllers/PieController.cs
using System.Collections.Generic;
using System.Linq;
using BethanysPieShop.Models;
using BethanysPieShop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BethanysPieShop.Controllers
{
    public class PieController : Controller
    {
        public PieController(IPieRepository pieRepository, ICategoryRepository categoryRepository)
        {
            this.pieRepository = pieRepository;
            this.categoryRepository = categoryRepository;
        }

        public ViewResult List(string category)
        {
            IEnumerable<Pie> pies;
            string currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                pies = pieRepository.AllPies.OrderBy(p => p.PieId);
                currentCategory = "All pies";
            }
            else
            {
                pies = pieRepository.AllPies.Where(p => p.Category.CategoryName == category)
                    .OrderBy(p => p.PieId);
                currentCategory = categoryRepository.AllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }

            return View(new PiesListViewModel
            {
                Pies = pies,
                CurrentCategory = currentCategory
            });
        }


        public IActionResult Details(int id)
        {
            var pie = pieRepository.GetPieById(id);
            if (pie == null)
                return NotFound();

            return View(pie);
        }

        //

        private readonly IPieRepository pieRepository;
        private readonly ICategoryRepository categoryRepository;
    }
}

BethanysPieShop/BethanysPieShop/Views/Shared/_Carousel.cshtml
<div class="row carousel-holder">
	<div class="col-md-12">
		<div id="carousel-example-generic" class="carousel slide-image" data-ride="carousel">
			<ol class="carousel-indicators">
				<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
				<li data-target="#carousel-example-generic" data-slide-to="1"></li>
				<li data-target="#carousel-example-generic" data-slide-to="2"></li>
			</ol>
			<div class="carousel-inner">
				<div class="item active">
					<img class="slide-image" src="~/Images/carousel1.jpg" alt="">
				</div>
				<div class="item">
					<img class="slide-image" src="~/Images/carousel2.jpg" alt="">
				</div>
				<div class="item">
					<img class="slide-image" src="~/Images/carousel3.jpg" alt="">
				</div>
			</div>
			<a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
				<span class="glyphicon glyphicon-chevron-left"></span>
			</a>
			<a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
				<span class="glyphicon glyphicon-chevron-right"></span>
			</a>
		</div>
	</div>
</div>

BethanysPieShop/BethanysPieShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/Content/site.css" rel="stylesheet" />
</head>
<body>
<div class="container">
    
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    @await Component.InvokeAsync("CategoryMenu")
                    <li><a asp-controller="Contact" asp-action="Index">Contact</a></li>
                    @await Component.InvokeAsync("ShoppingCartSummary")
                </ul>
            </div>
        </div>
    </nav>

    <div class="row">
        <div class="col-md-3">
            <p class="lead">
                <img class="img-responsive" alt="Bethany's Pie Shop'" src="~/Images/bethanylogo.png"/>
            </p>
        </div>
        <div class="col-md-9">
            @RenderBody()
        </div>
    </div>
</div>
</body>
</html>

BethanysPieShop/BethanysPieShop/Views/Shared/_PieCard.cshtml
@model Pie
<div class="col-sm-4 col-lg-4 col-md-4">
	<div class="thumbnail">
		<img src="@Model.ImageThumbnailUrl" alt="">
		<div class="caption">
			<h3 class="pull-right">@Model.Price.ToString("c")</h3>
			<h3>
				<a asp-controller="Pie"
				   asp-action="Details"
				   asp-route-id="@Model.PieId">@Model.Name</a>
			</h3>
			<p>@Model.ShortDescription</p>
		</div>
		<div class="addToCart">
			<p>
				<a class="btn btn-primary"
				   asp-controller="ShoppingCart"
				   asp-action="AddToShoppingCart"
				   asp-route-pieId="@Model.PieId">Add to cart</a>
			</p>
		</div>
	</div>
</div>